# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 635864426a0ab54b58272811226f9a56020a7003eeb81e8b37c72de6ac95f7936b5fe3f4a5eef64355af723c02699e06a4ec22a9e9709ab14ecee3b2379f1194

test:
  secret_key_base: bafd73876330f4a78590a6afcca488c4f8ddfbdd21b70c50e7331c5552ac928c2e925a2b237d56890177c52ce355208190afadb677a1992871db935fe4846ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
